-- MySQL Script generated by MySQL Workbench
-- Mon Feb 13 19:25:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cleaner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cleaner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cleaner` (
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cleaner_user1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` BIGINT NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`household`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`household` ;

CREATE TABLE IF NOT EXISTS `mydb`.`household` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_start` DATETIME NOT NULL,
  `customer_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_household_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_household_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`participant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`participant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `household_id` BIGINT NOT NULL,
  `service_id` BIGINT NOT NULL,
  `cleaner_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participant_household1_idx` (`household_id` ASC),
  INDEX `fk_participant_service1_idx` (`service_id` ASC),
  INDEX `fk_participant_cleaner1_idx` (`cleaner_id` ASC),
  CONSTRAINT `fk_participant_household1`
    FOREIGN KEY (`household_id`)
    REFERENCES `mydb`.`household` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_cleaner1`
    FOREIGN KEY (`cleaner_id`)
    REFERENCES `mydb`.`cleaner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_has_cleaner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_has_cleaner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_has_cleaner` (
  `service_id` BIGINT NOT NULL,
  `cleaner_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`service_id`, `cleaner_user_id`),
  INDEX `fk_service_has_cleaner_cleaner1_idx` (`cleaner_user_id` ASC),
  INDEX `fk_service_has_cleaner_service1_idx` (`service_id` ASC),
  CONSTRAINT `fk_service_has_cleaner_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_has_cleaner_cleaner1`
    FOREIGN KEY (`cleaner_user_id`)
    REFERENCES `mydb`.`cleaner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
